name: Build and Test iOS Application

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test iOS Application
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build and Test Example App
      run: |
          xcodebuild test \
            -project TestApp.xcodeproj \
            -scheme TestApp \
            -destination 'name=iPhone 14 Pro Max' \
            -enableCodeCoverage YES \
            -resultBundlePath TestAppUITests.xcresult \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
            sleep 300
          - name: install recorder and record session
                   run: |
                    brew install ffmpeg
                    $ANDROID_HOME/tools/emulator -port 18725 -verbose -no-window -no-audio -gpu swiftshader_indirect @Pixel_API_29_AOSP &
                    ffmpeg -f avfoundation -i 0 -t 600 out.mov
                # node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 120 out.mov'); exec.exec('$ANDROID_HOME/tools/emulator -port 18725 -verbose -no-window -no-audio -gpu swiftshader_indirect @Pixel_API_29_AOSP &');"
                   env:
                    HOMEBREW_NO_INSTALL_CLEANUP: 1
                 - name: upload video
                   uses: actions/upload-artifact@master
                   with:
                    name: out
                    path: out.mov
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestAppUITests.xcresult
        path: TestAppUITests.xcresult
